version: "3"

server:
  command: "php /app/vendor/bin/rr-worker"  # 根据你的 Yii3 项目调整路径
  relay: "pipes"

http:
  address: 0.0.0.0:8080
  pool:
    num_workers: 4
    max_jobs: 1000
    allocate_timeout: 60s
    destroy_timeout: 60s

logs:
  mode: development
  level: debug

static:
  dir: "/app/public"
  forbid: [".php", ".htaccess"]

rpc:
  listen: tcp://127.0.0.1:6001

# --- NATS / JetStream 驱动配置 ---
nats:
  # NATS 服务地址（在容器内部通过服务名 nats 访问）
  addr: "nats://nats:4222"

jobs:
  num_pollers: 10
  pipeline_size: 100000
  pool:
    num_workers: 10
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

  pipelines:
    # 一个示例队列管道：test-pipeline
    test-pipeline:
      driver: nats
      config:
        # NATS subject（主题）
        subject: "test.subject"
        # JetStream stream 名称（每个 pipeline 要用唯一 stream）
        stream: "test-stream"
        # 从当前时间之后投递的消息开始消费（不消费历史消息）
        deliver_new: true
        # 预取数量
        prefetch: 100
        # 优先级（可选）
        priority: 2
        # 删除 stream 当 pipeline 停止时（一般开发环境可以开 false，避免误删数据）
        delete_stream_on_stop: false
        # 消息 ack 后是否删除（可选）
        delete_after_ack: false
